"""Markdown output, suitable for a pull request comment or issue tracker.

The audience is different from the terminal's. Somebody reading this has not run
the tool and may not know what Amazon Quick is -- so the output has to stand on
its own: a summary table they can scan, then the failures in full with their
citations, then a short note on what the tool is.

Passing rules get a single table row. Failures get the whole story, because those
are the rows that will be argued about in review.
"""

from __future__ import annotations

from ..findings import Report, Status

_MARK = {
    Status.FAIL: "❌",
    Status.PASS: "✅",
    Status.SKIP: "⏭️",
    Status.ERROR: "⚠️",
}


def render(report: Report) -> str:
    lines: list[str] = []
    blockers = len(report.blockers)
    warnings = len(report.warnings)

    if blockers:
        verdict = f"**{blockers} blocker{'s' if blockers != 1 else ''}** — this server will not work with Amazon Quick."
    elif warnings:
        verdict = f"**{warnings} warning{'s' if warnings != 1 else ''}** — likely to work, with risks worth reading."
    else:
        verdict = "**No blockers found.**"

    lines += [
        "## Amazon Quick MCP preflight",
        "",
        f"`{report.target}`",
        "",
        verdict,
        "",
        f"{blockers} blockers · {warnings} warnings · {report.count(Status.PASS)} passed "
        f"· {report.count(Status.SKIP)} skipped · exit code `{report.exit_code()}`",
        "",
        "| | Rule | Severity | Result |",
        "|---|---|---|---|",
    ]

    for f in report.findings:
        measured = " ·  _measured_" if f.verified else ""
        lines.append(
            f"| {_MARK[f.status]} | `{f.rule_id}` | {f.severity.value} | {f.headline}{measured} |"
        )

    failures = [f for f in report.findings if f.status in (Status.FAIL, Status.ERROR)]
    if failures:
        lines += ["", "### What needs fixing", ""]
        for f in failures:
            lines += [f"#### `{f.rule_id}` — {f.title}", "", f"**{f.headline}**", ""]
            if f.detail:
                lines += ["\n".join(f.detail), ""]
            if f.remediation:
                lines += [f"**Fix:** {f.remediation}", ""]
            lines += [f"[Documentation]({f.doc_url})", ""]

    if report.probe_errors:
        lines += ["", "### The probe could not complete everything", ""]
        for key, value in report.probe_errors.items():
            lines.append(f"- `{key}`: {value}")
        lines.append("")

    lines += [
        "---",
        "",
        "<sub>Generated by [qs-preflight](https://github.com/tidika/qs-preflight). "
        "Rules marked _measured_ were verified against a live Amazon Quick account "
        "rather than derived from documentation alone.</sub>",
    ]
    return "\n".join(lines)
